name: Mirror to Codeberg

on:
  push:
    branches:
      - '**'
  create:
  delete:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        run: |
          git remote add codeberg https://thomasboom:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/thomasboom/BreathSpace.git
          git push --mirror codeberg
